### ISSUE TITLE
For Contao 4.6 needs to accept symphony framework bundle 4.1.x

### ISSUE THREAD

**Issue by MicioMax** [heimrichhannot/contao-request-bundle#1]
Hi,
about the same problem that was in contao-utils-bundle, for contao 4.6 we need to accept higher framework version.
`"symfony/framework-bundle": "^3.4",`
should be
`"symfony/framework-bundle": "^3.4|^4.1",`

**Comment by koertho** [comment]
Should be fixed in Version 1.0.6.
Thanks for reporting!
